name: property_app
description: Property rental app with map, messages, and bookings screens.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.6.0
  flutter_dotenv: ^5.0.3
  cached_network_image: ^3.3.1
  fl_chart: ^1.2.0
  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  phosphor_flutter: ^2.0.0
  iconify_flutter: ^0.0.7
  flutter_svg: ^2.3.0
  table_calendar: ^3.0.10
  url_launcher: ^6.1.10
  share_plus: ^10.0.0
  image_picker: ^1.2.3
  image_cropper: ^8.0.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  camera: ^0.12.0+1
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.2
  socket_io_client: ^2.0.0
  visibility_detector: ^0.4.0
  uuid: ^4.5.3
  google_sign_in: ^6.1.0

  flutter_webrtc: ^1.4.1
  firebase_core: ^4.10.0
  firebase_analytics: ^12.0.0
  firebase_messaging: ^16.3.0
  flutter_local_notifications: ^22.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/illustrations/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/illustrations/icon.png"
  # Android 13+ themed monochrome icon (Material You)
  adaptive_icon_monochrome_foreground: "assets/illustrations/app_icon_monochrome.png"
  monochrome_icon: "assets/illustration/app_icon_monochrome.png"


flutter:
  uses-material-design: true
  assets:
    - config.env
    - assets/images/
    - assets/illustrations/
