org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapBaseMinAddress=0x100000000 -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
android.useAndroidX=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
